// @ts-nocheck
/* eslint-disable */
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	appInfo: () => __TAURI_INVOKE<AppInfo>("app_info"),
	/**  Receives the result of a `SWITCHYARD_BENCH` run, prints it as one line of JSON and quits. */
	benchReport: (report: string) => __TAURI_INVOKE<void>("bench_report", { report }),
	projectsList: () => typedError<Project[], IpcError>(__TAURI_INVOKE("projects_list")),
	/**  Add the repository containing `path`. Fails with `not_a_git_repo` unless `init_git` is set. */
	projectOpen: (path: string, initGit: boolean) => typedError<AddedProject, IpcError>(__TAURI_INVOKE("project_open", { path, initGit })),
	projectCreate: (name: string, parent: string) => typedError<AddedProject, IpcError>(__TAURI_INVOKE("project_create", { name, parent })),
	/**  Forget a project. Files on disk are never touched. */
	projectRemove: (id: string) => typedError<null, IpcError>(__TAURI_INVOKE("project_remove", { id })),
	projectsReorder: (orderedIds: string[]) => typedError<null, IpcError>(__TAURI_INVOKE("projects_reorder", { orderedIds })),
	uiStateLoad: () => typedError<{ [key in string]: string }, IpcError>(__TAURI_INVOKE("ui_state_load")),
	uiStateSave: (key: string, value: string) => typedError<null, IpcError>(__TAURI_INVOKE("ui_state_save", { key, value })),
	harnessesList: () => typedError<HarnessInfo[], IpcError>(__TAURI_INVOKE("harnesses_list")),
	/**
	 *  Save a harness definition. For a built-in only the differences from the shipped definition
	 *  are stored; saving one identical to it removes the override.
	 */
	harnessSave: (def: HarnessDef) => typedError<HarnessInfo[], IpcError>(__TAURI_INVOKE("harness_save", { def })),
	/**  Restore a built-in to its shipped definition, or delete a custom harness. */
	harnessReset: (id: string) => typedError<HarnessInfo[], IpcError>(__TAURI_INVOKE("harness_reset", { id })),
	/**  What would run for this — possibly unsaved — definition, with sample values filled in. */
	harnessPreview: (def: HarnessDef) => typedError<HarnessPreview, IpcError>(__TAURI_INVOKE("harness_preview", { def })),
	/**
	 *  Start this — possibly unsaved — definition in the home directory, with no prompt, to see
	 *  whether it comes up. The caller shows the session and closes it.
	 */
	harnessTest: (def: HarnessDef, size: TermSize) => typedError<SessionInfo, IpcError>(__TAURI_INVOKE("harness_test", { def, size })),
	settingsGet: () => typedError<SettingsInfo, IpcError>(__TAURI_INVOKE("settings_get")),
	settingsSaveWorkspaces: (workspaces: WorkspaceSettingsDto) => typedError<SettingsInfo, IpcError>(__TAURI_INVOKE("settings_save_workspaces", { workspaces })),
	projectBranches: (projectId: string) => typedError<BranchList, IpcError>(__TAURI_INVOKE("project_branches", { projectId })),
	/**
	 *  The core loop: make a worktree — on a new branch, or for an existing one — and start a harness in it with the user's
	 *  first message. If the harness cannot start, the worktree and branch are taken back, so a
	 *  failed attempt leaves no trace.
	 */
	workspaceCreate: (request: NewWorkspace) => typedError<CreatedWorkspace, IpcError>(__TAURI_INVOKE("workspace_create", { request })),
	/**  Remove a workspace's worktree. The branch is kept. Fails with `worktree_dirty` unless `force`. */
	workspaceDelete: (id: string, force: boolean) => typedError<null, IpcError>(__TAURI_INVOKE("workspace_delete", { id, force })),
	envInfo: (reload: boolean) => typedError<EnvInfo, IpcError>(__TAURI_INVOKE("env_info", { reload })),
	ptySpawn: (request: SpawnRequest) => typedError<SessionInfo, IpcError>(__TAURI_INVOKE("pty_spawn", { request })),
	/**  Stream a session into `output`: first a snapshot that repaints the terminal, then live bytes. */
	ptyAttach: (id: SessionId, output: Channel<RawBytes>) => typedError<number, IpcError>(__TAURI_INVOKE("pty_attach", { id, output })),
	ptyDetach: (id: SessionId, attachment: number) => typedError<null, IpcError>(__TAURI_INVOKE("pty_detach", { id, attachment })),
	ptyWrite: (id: SessionId, data: string) => typedError<null, IpcError>(__TAURI_INVOKE("pty_write", { id, data })),
	ptyResize: (id: SessionId, size: TermSize) => typedError<null, IpcError>(__TAURI_INVOKE("pty_resize", { id, size })),
	ptyKill: (id: SessionId) => typedError<null, IpcError>(__TAURI_INVOKE("pty_kill", { id })),
	/**  Kill (if needed) and forget a session. */
	ptyClose: (id: SessionId) => typedError<null, IpcError>(__TAURI_INVOKE("pty_close", { id })),
	ptyList: () => typedError<SessionInfo[], IpcError>(__TAURI_INVOKE("pty_list")),
};

/** Events */
export const events = {
	ptyHostEvent: makeEvent<PtyHostEvent>("pty-host-event"),
};

/* Types */
/**  The result of adding a project: it may have been known already. */
export type AddedProject = {
	project: Project,
	alreadyKnown: boolean,
	/**  Set when the chosen folder was inside a repository and its root was added instead. */
	openedRootInstead: boolean,
};

/**  Static facts about the running app, shown in the UI and useful in bug reports. */
export type AppInfo = {
	name: string,
	version: string,
	/**  `linux`, `macos` or `windows`. */
	os: string,
	arch: string,
	debug: boolean,
	dev: DevFlags,
};

export type BranchList = {
	branches: string[],
	/**  The branch to offer first: the remote's default, or the one checked out. */
	default: string | null,
	/**
	 *  Branches checked out in some worktree already. Git allows a branch in one place only, so
	 *  these cannot be opened as a workspace.
	 */
	checkedOut: string[],
};

export type CreatedWorkspace = {
	workspace: Workspace,
	session: SessionInfo,
};

/**
 *  Switches for measuring and debugging, read from the environment. Always empty in release
 *  builds.
 */
export type DevFlags = {
	/**
	 *  `SWITCHYARD_BENCH`: a shell script to run in a terminal while frame times are recorded;
	 *  the app prints the result and exits. See `docs/07-terminal-benchmarks.md`.
	 */
	bench: string | null,
	/**  `SWITCHYARD_RENDERER`: force the terminal renderer (`webgl` or `dom`). */
	renderer: string | null,
};

/**  What the launch environment looks like, for the status bar and for bug reports. */
export type EnvInfo = {
	source: EnvSource,
	shell: string,
	pathEntries: number,
	warning: string | null,
};

export type EnvSource = 
/**  Captured from the user's login shell. */
"loginShell" | 
/**  This process's own environment: always on Windows, and the fallback elsewhere. */
"process";

export type ExitInfo = {
	code: number,
	success: boolean,
	/**  Name of the terminating signal, where the platform reports one. */
	signal: string | null,
};

export type HarnessDef = {
	/**  Stable key, recorded with sessions. */
	id: string,
	label: string,
	command: string,
	/**  Always passed. */
	baseArgs: string[],
	modelArgs: string[],
	effortArgs: string[],
	sessionArgs: string[],
	promptArgs: string[],
	resumeArgs: string[],
	forkArgs: string[],
	/**  Effort levels to offer. Empty hides the picker. */
	efforts: string[],
	/**  Model suggestions. Free text is always accepted: names change faster than we ship. */
	models: string[],
	promptTransport: PromptTransport,
	sessionIdMode: SessionIdMode,
	/**
	 *  With the `stdin` transport: how long the harness must have been quiet, after printing
	 *  something, before the prompt is pasted.
	 */
	stdinReadyMs: number,
	/**  Disabled harnesses stay configured but are not offered. */
	enabled: boolean,
};

/**  A harness definition plus whether its command can be found on this machine. */
export type HarnessInfo = {
	/**  Where `command` resolved to on the user's `PATH`; `None` if it is not installed. */
	resolvedPath: string | null,
	/**  Ships with Switchyard (as opposed to one the user added). */
	builtin: boolean,
	/**  A built-in whose definition the user has changed. */
	modified: boolean,
} & HarnessDef;

/**  The exact command lines a definition produces, for the settings form to show. */
export type HarnessPreview = {
	resolvedPath: string | null,
	start: string[],
	resume: string[],
	fork: string[],
	/**  Why this definition cannot be saved as it stands, if it cannot. */
	problem: string | null,
};

/**  Which harness to start, and with what. */
export type HarnessRequest = {
	id: string,
	/**  `None` or empty: let the harness use its own default. */
	model: string | null,
	effort: string | null,
	/**  The first message. `None` or empty just opens the harness. */
	prompt: string | null,
};

export type HeadInfo = {
	/**  Branch name, or the abbreviated commit when detached. */
	label: string,
	detached: boolean,
	/**  The branch has no commits yet. */
	unborn: boolean,
};

/**  Host-wide notifications, delivered to the sink given to [`crate::PtyHost::new`]. */
export type HostEvent = 
/**  The session's process ended and all of its output has been delivered. */
{ type: "exited"; id: SessionId; exit: ExitInfo };

/**
 *  The one error shape that crosses IPC: a stable `code` for the UI to branch on and a
 *  human-readable `message` to show.
 */
export type IpcError = {
	code: string,
	message: string,
};

export type NewWorkspace = {
	projectId: string,
	/**  `None` starts from the project's default branch. */
	baseBranch: string | null,
	/**  Open this existing branch instead of creating a new one; `base_branch` is then ignored. */
	existingBranch: string | null,
	harness: HarnessRequest,
	size: TermSize,
};

export type Project = {
	id: string,
	name: string,
	rootPath: string,
	/**
	 *  The folder is gone (deleted, moved, or on an unmounted drive). The project is kept so it
	 *  reappears by itself if the folder does; the user can remove it.
	 */
	missing: boolean,
	workspaces: Workspace[],
};

export type PromptTransport = 
/**  The prompt is an argument. Simple and reliable. */
"argv" | 
/**
 *  The prompt is pasted into the terminal once the harness has started and gone quiet. For
 *  harnesses with no prompt argument, and for prompts too long for a command line.
 */
"stdin";

/**  Emitted for every [`HostEvent`]. */
export type PtyHostEvent = HostEvent;

/**
 *  Terminal output, sent over the channel as raw bytes rather than JSON: the webview receives
 *  an `ArrayBuffer` it can hand straight to xterm.js.
 * 
 *  The generated binding types this as `number[]` because specta only sees the `Vec<u8>`;
 *  `src/lib/ipc.ts` corrects that in one place.
 */
export type RawBytes = number[];

/**  Opaque, globally unique session identifier. */
export type SessionId = string;

export type SessionIdMode = 
/**  We choose the harness's session id up front, so resume is deterministic. */
"assigned" | 
/**
 *  The harness picks; we resume "the latest session in this directory", which is safe
 *  because every workspace has a directory of its own.
 */
"latestInCwd";

export type SessionInfo = {
	id: SessionId,
	program: string,
	args: string[],
	cwd: string | null,
	pid: number | null,
	size: TermSize,
	labels: { [key in string]: string },
	state: SessionState,
	/**
	 *  Whether the program has printed anything yet. With `idle_ms` this tells "still starting"
	 *  from "started and now waiting", without anyone parsing what it printed.
	 */
	hasOutput: boolean,
	/**
	 *  Milliseconds since the session last produced output (saturating). Drives "busy / waiting" indicators
	 *  without anyone having to parse what the program printed.
	 */
	idleMs: number,
};

export type SessionState = { status: "running" } | { status: "exited"; exit: ExitInfo };

export type SettingsInfo = {
	workspaces: WorkspaceSettingsDto,
	defaultWorktreeRoot: string,
	/**  Set while `SWITCHYARD_WORKTREE_ROOT` overrides the setting. */
	worktreeRootOverride: string | null,
	filePath: string,
	/**  Why the settings file was ignored, if it was (it is kept, never overwritten). */
	problem: string | null,
};

export type SpawnRequest = {
	/**  Program to run. `None` starts the user's shell. */
	program: string | null,
	args?: string[],
	/**  Working directory. `None` means the home directory. Ignored when `workspace_id` is set. */
	cwd: string | null,
	/**
	 *  Run inside this workspace: the core looks up its folder (the webview never supplies
	 *  paths for this) and labels the session so it can be matched back to the workspace.
	 */
	workspaceId: string | null,
	/**  Run a harness instead of `program`. Requires `workspace_id`. */
	harness: HarnessRequest | null,
	size: TermSize,
};

export type TermSize = {
	cols: number,
	rows: number,
};

export type Workspace = {
	id: string,
	projectId: string,
	kind: WorkspaceKind,
	name: string,
	path: string,
	/**  What is checked out right now, asked of git at listing time. */
	head: HeadInfo | null,
	/**  The folder is gone. Only deleting the workspace makes sense then. */
	missing: boolean,
};

export type WorkspaceKind = 
/**  The project's own checkout. Always present, never deletable. */
"local" | 
/**  A git worktree on its own branch. */
"worktree";

export type WorkspaceSettingsDto = {
	/**  `None` uses `default_worktree_root`. */
	worktreeRoot: string | null,
	branchPrefix: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

