// @ts-nocheck
/* eslint-disable */
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	appInfo: () => __TAURI_INVOKE<AppInfo>("app_info"),
};

/* Types */
/**  Static facts about the running app, shown in the UI and useful in bug reports. */
export type AppInfo = {
	name: string,
	version: string,
	/**  `linux`, `macos` or `windows`. */
	os: string,
	arch: string,
	debug: boolean,
};

