// @ts-nocheck
/* eslint-disable */
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	appInfo: () => __TAURI_INVOKE<AppInfo>("app_info"),
	/**  Receives the result of a `SWITCHYARD_BENCH` run, prints it as one line of JSON and quits. */
	benchReport: (report: string) => __TAURI_INVOKE<void>("bench_report", { report }),
	projectsList: () => typedError<Project[], IpcError>(__TAURI_INVOKE("projects_list")),
	/**  Add the repository containing `path`. Fails with `not_a_git_repo` unless `init_git` is set. */
	projectOpen: (path: string, initGit: boolean) => typedError<AddedProject, IpcError>(__TAURI_INVOKE("project_open", { path, initGit })),
	projectCreate: (name: string, parent: string) => typedError<AddedProject, IpcError>(__TAURI_INVOKE("project_create", { name, parent })),
	/**  Forget a project. Files on disk are never touched. */
	projectRemove: (id: string) => typedError<null, IpcError>(__TAURI_INVOKE("project_remove", { id })),
	projectsReorder: (orderedIds: string[]) => typedError<null, IpcError>(__TAURI_INVOKE("projects_reorder", { orderedIds })),
	uiStateLoad: () => typedError<{ [key in string]: string }, IpcError>(__TAURI_INVOKE("ui_state_load")),
	uiStateSave: (key: string, value: string) => typedError<null, IpcError>(__TAURI_INVOKE("ui_state_save", { key, value })),
	envInfo: (reload: boolean) => typedError<EnvInfo, IpcError>(__TAURI_INVOKE("env_info", { reload })),
	ptySpawn: (request: SpawnRequest) => typedError<SessionInfo, IpcError>(__TAURI_INVOKE("pty_spawn", { request })),
	/**  Stream a session into `output`: first a snapshot that repaints the terminal, then live bytes. */
	ptyAttach: (id: SessionId, output: Channel<RawBytes>) => typedError<number, IpcError>(__TAURI_INVOKE("pty_attach", { id, output })),
	ptyDetach: (id: SessionId, attachment: number) => typedError<null, IpcError>(__TAURI_INVOKE("pty_detach", { id, attachment })),
	ptyWrite: (id: SessionId, data: string) => typedError<null, IpcError>(__TAURI_INVOKE("pty_write", { id, data })),
	ptyResize: (id: SessionId, size: TermSize) => typedError<null, IpcError>(__TAURI_INVOKE("pty_resize", { id, size })),
	ptyKill: (id: SessionId) => typedError<null, IpcError>(__TAURI_INVOKE("pty_kill", { id })),
	/**  Kill (if needed) and forget a session. */
	ptyClose: (id: SessionId) => typedError<null, IpcError>(__TAURI_INVOKE("pty_close", { id })),
	ptyList: () => typedError<SessionInfo[], IpcError>(__TAURI_INVOKE("pty_list")),
};

/** Events */
export const events = {
	ptyHostEvent: makeEvent<PtyHostEvent>("pty-host-event"),
};

/* Types */
/**  The result of adding a project: it may have been known already. */
export type AddedProject = {
	project: Project,
	alreadyKnown: boolean,
	/**  Set when the chosen folder was inside a repository and its root was added instead. */
	openedRootInstead: boolean,
};

/**  Static facts about the running app, shown in the UI and useful in bug reports. */
export type AppInfo = {
	name: string,
	version: string,
	/**  `linux`, `macos` or `windows`. */
	os: string,
	arch: string,
	debug: boolean,
	dev: DevFlags,
};

/**
 *  Switches for measuring and debugging, read from the environment. Always empty in release
 *  builds.
 */
export type DevFlags = {
	/**
	 *  `SWITCHYARD_BENCH`: a shell script to run in a terminal while frame times are recorded;
	 *  the app prints the result and exits. See `docs/07-terminal-benchmarks.md`.
	 */
	bench: string | null,
	/**  `SWITCHYARD_RENDERER`: force the terminal renderer (`webgl` or `dom`). */
	renderer: string | null,
};

/**  What the launch environment looks like, for the status bar and for bug reports. */
export type EnvInfo = {
	source: EnvSource,
	shell: string,
	pathEntries: number,
	warning: string | null,
};

export type EnvSource = 
/**  Captured from the user's login shell. */
"loginShell" | 
/**  This process's own environment: always on Windows, and the fallback elsewhere. */
"process";

export type ExitInfo = {
	code: number,
	success: boolean,
	/**  Name of the terminating signal, where the platform reports one. */
	signal: string | null,
};

export type HeadInfo = {
	/**  Branch name, or the abbreviated commit when detached. */
	label: string,
	detached: boolean,
	/**  The branch has no commits yet. */
	unborn: boolean,
};

/**  Host-wide notifications, delivered to the sink given to [`crate::PtyHost::new`]. */
export type HostEvent = 
/**  The session's process ended and all of its output has been delivered. */
{ type: "exited"; id: SessionId; exit: ExitInfo };

/**
 *  The one error shape that crosses IPC: a stable `code` for the UI to branch on and a
 *  human-readable `message` to show.
 */
export type IpcError = {
	code: string,
	message: string,
};

export type Project = {
	id: string,
	name: string,
	rootPath: string,
	/**
	 *  The folder is gone (deleted, moved, or on an unmounted drive). The project is kept so it
	 *  reappears by itself if the folder does; the user can remove it.
	 */
	missing: boolean,
	workspaces: Workspace[],
};

/**  Emitted for every [`HostEvent`]. */
export type PtyHostEvent = HostEvent;

/**
 *  Terminal output, sent over the channel as raw bytes rather than JSON: the webview receives
 *  an `ArrayBuffer` it can hand straight to xterm.js.
 * 
 *  The generated binding types this as `number[]` because specta only sees the `Vec<u8>`;
 *  `src/lib/ipc.ts` corrects that in one place.
 */
export type RawBytes = number[];

/**  Opaque, globally unique session identifier. */
export type SessionId = string;

export type SessionInfo = {
	id: SessionId,
	program: string,
	args: string[],
	cwd: string | null,
	pid: number | null,
	size: TermSize,
	labels: { [key in string]: string },
	state: SessionState,
	/**
	 *  Milliseconds since the session last produced output (saturating). Drives "busy / waiting" indicators
	 *  without anyone having to parse what the program printed.
	 */
	idleMs: number,
};

export type SessionState = { status: "running" } | { status: "exited"; exit: ExitInfo };

export type SpawnRequest = {
	/**  Program to run. `None` starts the user's shell. */
	program: string | null,
	args?: string[],
	/**  Working directory. `None` means the home directory. Ignored when `workspace_id` is set. */
	cwd: string | null,
	/**
	 *  Run inside this workspace: the core looks up its folder (the webview never supplies
	 *  paths for this) and labels the session so it can be matched back to the workspace.
	 */
	workspaceId: string | null,
	size: TermSize,
};

export type TermSize = {
	cols: number,
	rows: number,
};

export type Workspace = {
	id: string,
	projectId: string,
	kind: WorkspaceKind,
	name: string,
	path: string,
	/**  What is checked out right now, asked of git at listing time. */
	head: HeadInfo | null,
};

export type WorkspaceKind = 
/**  The project's own checkout. Always present, never deletable. */
"local" | 
/**  A git worktree on its own branch. */
"worktree";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

